site_name: My Guide
theme:
  name: terminal
nav:
    - Home: 'index.md'
    - Troubleshooting: 'help.md'
    - About: 
      - Contributing: 'about/contributing.md'
      - License: 'about/license.md'
      - Release Notes:
        - v1: 'about/release-notes/version-1.md'
        - v2: 'about/release-notes/version-2.md'
  
